DEFAULT_ACHIEVEMENTS = [
    {
        "id": "achievement-1",
        "name": "Habit Guru",
        "description": "Complete 500 habits total",
        "category": "habits",
        "image": "/achievements/habit-guru.png",
        "rarity": "epic",
        "earned": False,
        "earnedDate": None,
        "progress": 0,
        "total": 500,
        "coinReward": 250,
        "claimed": False
    },
    {
        "id": "achievement-2",
        "name": "30-Day Champion",
        "description": "Maintain a 30-day streak on any habit",
        "category": "streaks",
        "image": "/achievements/30-day-champion.png",
        "rarity": "epic",
        "earned": False,
        "earnedDate": None,
        "progress": 0,
        "total": 30,
        "coinReward": 200,
        "claimed": False
    },
    {
        "id": "achievement-3",
        "name": "100-Day Legend",
        "description": "Maintain a 100-day streak on any habit",
        "category": "streaks",
        "image": "/achievements/100-day-legend.png",
        "rarity": "legendary",
        "earned": False,
        "earnedDate": None,
        "progress": 0,
        "total": 100,
        "coinReward": 400,
        "claimed": False
    },
    {
        "id": "achievement-4",
        "name": "Perfect Week",
        "description": "Complete all your habits for 7 consecutive days",
        "category": "streaks",
        "image": "/achievements/perfect-week.png",
        "rarity": "rare",
        "earned": False,
        "earnedDate": None,
        "progress": 0,
        "total": 7,
        "coinReward": 125,
        "claimed": False
    },
    {
        "id": "achievement-5",
        "name": "First Milestone",
        "description": "Complete your first 50 habits total",
        "category": "habits",
        "image": "/achievements/first-milestone.png",
        "rarity": "common",
        "earned": False,
        "earnedDate": None,
        "progress": 0,
        "total": 50,
        "coinReward": 50,
        "claimed": False
    },
    {
        "id": "achievement-6",
        "name": "Productivity Master",
        "description": "Complete 1000 habits total",
        "category": "habits",
        "image": "/achievements/productivity-master.png",
        "rarity": "legendary",
        "earned": False,
        "earnedDate": None,
        "progress": 0,
        "total": 1000,
        "coinReward": 500,
        "claimed": False
    },
    {
        "id": "achievement-7",
        "name": "Consistency King",
        "description": "Complete at least one habit every day for 30 days",
        "category": "streaks",
        "image": "/achievements/consistency-king.png",
        "rarity": "epic",
        "earned": False,
        "earnedDate": None,
        "progress": 0,
        "total": 30,
        "coinReward": 250,
        "claimed": False
    },
    {
        "id": "achievement-8",
        "name": "test",
        "description": "testing",
        "category": "habits",
        "image": "/achievements/first-milestone.png",
        "rarity": "common",
        "earned": False,
        "earnedDate": None,
        "progress": 0,
        "total": 1,
        "coinReward": 50,
        "claimed": False
    },
]